/**
 * ArchitectureBlueprint — A plan for assembling blocks into a structure.
 *
 * A blueprint is the intermediate representation between an architectural
 * concept ("build a cathedral") and the actual block placement in the world.
 *
 * Blueprints are:
 * - Generated by the ArchitectureRuleEngine from archetypes + ArtDNA
 * - Validated for structural integrity before construction begins
 * - Built block-by-block by citizens (bottom-up, foundations first)
 * - Influenced by the agent's art style (colors, proportions, detail)
 *
 * This is where the LegoGen concept meets the game world:
 * Like LegoGen's classical generator building temples from CUBE/WEDGE/CYLINDER
 * blocks, blueprints define structures as ordered collections of typed blocks.
 */

import {
  type Block,
  type BlockParameters,
  BlockShape,
  BlockMaterial,
  BlockRole,
  StructureArchetype,
  BLOCK_MATERIAL_STRENGTH,
} from '../types/blocks';
import type { ArtDNA } from './types';

// ─── Blueprint Definition ───────────────────────────────────────────

/**
 * A complete architectural blueprint — the plan for a structure.
 */
export interface ArchitectureBlueprint {
  /** Unique blueprint ID */
  id: string;

  /** Human-readable name */
  name: string;

  /** What archetype this was generated from */
  archetype: StructureArchetype;

  /** Overall dimensions of the structure bounding box */
  bounds: { width: number; height: number; depth: number };

  /** All blocks that compose this structure, in build order */
  blocks: Block[];

  /** Total block count by role */
  blockCounts: Partial<Record<BlockRole, number>>;

  /** Total block count by material */
  materialCounts: Partial<Record<BlockMaterial, number>>;

  /** Build phases — blocks grouped by construction order */
  phases: BuildPhase[];

  /** Cultural value this structure will add when complete */
  culturalValue: number;

  /** Structural integrity score (0-1, 1 = fully sound) */
  structuralIntegrity: number;

  /** The ArtDNA that influenced this blueprint's generation */
  artDNAGeneration: number;

  /** Metadata from generation */
  metadata: BlueprintMetadata;
}

/**
 * A construction phase — blocks that can be built in parallel.
 * Phases are executed in order (foundation → walls → roof).
 */
export interface BuildPhase {
  /** Phase name for display */
  name: string;

  /** Block IDs in this phase (indexes into blueprint.blocks) */
  blockIds: number[];

  /** Minimum Y level of blocks in this phase */
  minY: number;

  /** Whether this phase requires the previous phase to be complete */
  requiresPrevious: boolean;
}

/**
 * Extra data about how a blueprint was generated.
 */
export interface BlueprintMetadata {
  /** Rule engine version that generated this */
  ruleVersion: number;

  /** Seed used for generation */
  seed: number;

  /** Generation timestamp */
  generatedAt: number;

  /** Custom description from operator command (if any) */
  operatorDescription?: string;

  /** Rule IDs that were active during generation */
  activeRules: string[];
}

// ─── Blueprint Generation Helpers ───────────────────────────────────

let nextBlockId = 0;

/**
 * Create a single block with sensible defaults.
 */
export function createBlock(
  shape: BlockShape,
  material: BlockMaterial,
  position: { x: number; y: number; z: number },
  dimensions: { w: number; h: number; d: number },
  role: BlockRole,
  params?: Partial<BlockParameters>,
  color?: { r: number; g: number; b: number; a: number },
): Block {
  return {
    id: nextBlockId++,
    shape,
    material,
    position: { ...position },
    dimensions: { ...dimensions },
    parameters: params ?? {},
    color: color ?? null,
    role,
  };
}

/**
 * Reset block ID counter (for testing).
 */
export function resetBlockIds(): void {
  nextBlockId = 0;
}

/**
 * Apply ArtDNA color influence to a block.
 * Converts the agent's color genes into RGBA values based on role.
 */
export function applyArtDNAColor(
  block: Block,
  artDNA: ArtDNA,
): void {
  const gene =
    block.role === 'Roof' ? artDNA.roofColor :
    block.role === 'Decoration' || block.role === 'Capital' || block.role === 'Entablature'
      ? artDNA.accentColor :
    artDNA.primaryColor;

  // HSL → RGB (simplified)
  const h = gene.hue / 360;
  const s = gene.saturation;
  const l = gene.lightness;

  // Add variance
  const variance = gene.variance;
  const hVar = (Math.random() - 0.5) * variance * 0.1;
  const sVar = (Math.random() - 0.5) * variance * 0.1;
  const lVar = (Math.random() - 0.5) * variance * 0.1;

  const rgb = hslToRgb(
    Math.max(0, Math.min(1, h + hVar)),
    Math.max(0, Math.min(1, s + sVar)),
    Math.max(0, Math.min(1, l + lVar)),
  );

  block.color = { r: rgb[0], g: rgb[1], b: rgb[2], a: 255 };
}

/**
 * HSL to RGB conversion.
 */
function hslToRgb(h: number, s: number, l: number): [number, number, number] {
  let r: number, g: number, b: number;

  if (s === 0) {
    r = g = b = l;
  } else {
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    r = hueToRgb(p, q, h + 1 / 3);
    g = hueToRgb(p, q, h);
    b = hueToRgb(p, q, h - 1 / 3);
  }

  return [Math.round(r * 255), Math.round(g * 255), Math.round(b * 255)];
}

function hueToRgb(p: number, q: number, t: number): number {
  if (t < 0) t += 1;
  if (t > 1) t -= 1;
  if (t < 1 / 6) return p + (q - p) * 6 * t;
  if (t < 1 / 2) return q;
  if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
  return p;
}

// ─── Build Phase Computation ────────────────────────────────────────

/**
 * Compute build phases from a list of blocks.
 * Groups blocks by Y level and structural dependency.
 *
 * Build order:
 * 1. Foundation (lowest Y blocks)
 * 2. Walls & Columns (mid-level, depends on foundation)
 * 3. Beams & Arches (horizontal spans, depends on walls)
 * 4. Roof (highest Y blocks, depends on walls)
 * 5. Decoration (last, depends on structure)
 */
export function computeBuildPhases(blocks: Block[]): BuildPhase[] {
  // Group blocks by role category
  const foundations: number[] = [];
  const structure: number[] = [];
  const spans: number[] = [];
  const roofs: number[] = [];
  const decorations: number[] = [];

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];
    switch (block.role) {
      case BlockRole.Foundation:
      case BlockRole.Access:
        foundations.push(i);
        break;
      case BlockRole.Wall:
      case BlockRole.Column:
      case BlockRole.Floor:
        structure.push(i);
        break;
      case BlockRole.Beam:
      case BlockRole.Vault:
      case BlockRole.Opening:
      case BlockRole.Entablature:
        spans.push(i);
        break;
      case BlockRole.Roof:
      case BlockRole.Pediment:
        roofs.push(i);
        break;
      case BlockRole.Decoration:
      case BlockRole.Capital:
        decorations.push(i);
        break;
    }
  }

  const phases: BuildPhase[] = [];

  if (foundations.length > 0) {
    const minY = Math.min(...foundations.map(i => blocks[i].position.y));
    phases.push({
      name: 'Foundation',
      blockIds: foundations,
      minY,
      requiresPrevious: false,
    });
  }

  if (structure.length > 0) {
    // Sort structure blocks by Y level (build bottom-up)
    structure.sort((a, b) => blocks[a].position.y - blocks[b].position.y);
    const minY = blocks[structure[0]].position.y;
    phases.push({
      name: 'Structure',
      blockIds: structure,
      minY,
      requiresPrevious: true,
    });
  }

  if (spans.length > 0) {
    const minY = Math.min(...spans.map(i => blocks[i].position.y));
    phases.push({
      name: 'Spanning',
      blockIds: spans,
      minY,
      requiresPrevious: true,
    });
  }

  if (roofs.length > 0) {
    const minY = Math.min(...roofs.map(i => blocks[i].position.y));
    phases.push({
      name: 'Roofing',
      blockIds: roofs,
      minY,
      requiresPrevious: true,
    });
  }

  if (decorations.length > 0) {
    const minY = Math.min(...decorations.map(i => blocks[i].position.y));
    phases.push({
      name: 'Decoration',
      blockIds: decorations,
      minY,
      requiresPrevious: true,
    });
  }

  return phases;
}

// ─── Blueprint Validation ───────────────────────────────────────────

/**
 * Validate structural integrity of a blueprint.
 * Checks that:
 * 1. Foundation blocks exist at the bottom
 * 2. Structural blocks have support below them
 * 3. Material strength supports the weight above
 *
 * Returns integrity score 0-1.
 */
export function validateBlueprint(blueprint: ArchitectureBlueprint): number {
  const blocks = blueprint.blocks;
  if (blocks.length === 0) return 0;

  let issues = 0;
  let checks = 0;

  // Check 1: Foundation exists at ground level
  const hasFoundation = blocks.some(
    b => b.role === BlockRole.Foundation && b.position.y <= 0.5
  );
  checks++;
  if (!hasFoundation) issues++;

  // Check 2: Every non-foundation block has support
  for (const block of blocks) {
    if (block.role === BlockRole.Foundation) continue;
    if (block.role === BlockRole.Decoration) continue; // Decorations can float

    checks++;
    const hasSupport = blocks.some(other => {
      if (other === block) return false;
      // Check if other block is directly below
      const dx = Math.abs(other.position.x - block.position.x);
      const dz = Math.abs(other.position.z - block.position.z);
      const dy = block.position.y - (other.position.y + other.dimensions.h);
      return dx < (other.dimensions.w / 2 + block.dimensions.w / 2) &&
             dz < (other.dimensions.d / 2 + block.dimensions.d / 2) &&
             dy >= -0.1 && dy < 0.5;
    });

    if (!hasSupport && block.position.y > 0.5) {
      issues++;
    }
  }

  // Check 3: Material strength
  // Sum weight above each foundation block
  for (const foundation of blocks.filter(b => b.role === BlockRole.Foundation)) {
    checks++;
    const strength = BLOCK_MATERIAL_STRENGTH[foundation.material];
    const blocksAbove = blocks.filter(b =>
      b !== foundation &&
      Math.abs(b.position.x - foundation.position.x) < foundation.dimensions.w &&
      Math.abs(b.position.z - foundation.position.z) < foundation.dimensions.d &&
      b.position.y > foundation.position.y
    ).length;

    if (blocksAbove > strength * 3) {
      issues++;
    }
  }

  return checks > 0 ? Math.max(0, 1 - issues / checks) : 0;
}

// ─── Blueprint Statistics ───────────────────────────────────────────

/**
 * Compute block counts by role and material for a blueprint.
 */
export function computeBlockCounts(blocks: Block[]): {
  byRole: Partial<Record<BlockRole, number>>;
  byMaterial: Partial<Record<BlockMaterial, number>>;
} {
  const byRole: Partial<Record<BlockRole, number>> = {};
  const byMaterial: Partial<Record<BlockMaterial, number>> = {};

  for (const block of blocks) {
    byRole[block.role] = (byRole[block.role] ?? 0) + 1;
    byMaterial[block.material] = (byMaterial[block.material] ?? 0) + 1;
  }

  return { byRole, byMaterial };
}

/**
 * Compute bounding box of a set of blocks.
 */
export function computeBounds(blocks: Block[]): { width: number; height: number; depth: number } {
  if (blocks.length === 0) return { width: 0, height: 0, depth: 0 };

  let minX = Infinity, maxX = -Infinity;
  let minY = Infinity, maxY = -Infinity;
  let minZ = Infinity, maxZ = -Infinity;

  for (const b of blocks) {
    const halfW = b.dimensions.w / 2;
    const halfD = b.dimensions.d / 2;
    minX = Math.min(minX, b.position.x - halfW);
    maxX = Math.max(maxX, b.position.x + halfW);
    minY = Math.min(minY, b.position.y);
    maxY = Math.max(maxY, b.position.y + b.dimensions.h);
    minZ = Math.min(minZ, b.position.z - halfD);
    maxZ = Math.max(maxZ, b.position.z + halfD);
  }

  return {
    width: maxX - minX,
    height: maxY - minY,
    depth: maxZ - minZ,
  };
}
